# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1.5-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - deploy:
          name: Deploy to host if branch is master
          command: |
               if [ "${CIRCLE_BRANCH}" == "master" ]; then
                apt-get update
                apt-get -qq install git-ftp
                echo "'_$(git status -uno --porcelain | wc -l)_'"
                git status -uno --porcelain
                echo "Initiating Push"
                git ftp init --user "${FTP_USER}" --passwd "${FTP_PASS}" "ftp://${FTP_HOST}:${FTP_PORT}/public_html"
               else
                echo "Not master branch so not deploying"
               fi

      # run tests!
      #- run: phpunit